git:
  depth: 1
language: node_js
node_js:
  - '4.2'
  - 'stable'
cache:
  directories:
    - node_modules
before_script:
  - npm set progress=false
  - npm install gulp-cli -g
  - chmod +x ./deploy-gh-pages.sh
script: "./deploy-gh-pages.sh"
env:
  global:
  - secure: "KERULo9ZWu7g/jZrOyUfmFsm8stO72L1qolLH3wX29N4yb6kdR1Go5OvxTMqIgxBD3/XXeZBdpXEJ9vqbKwZ7Xu5LL/ndF74aOGpc/h2rxFeuzulfupjYu63FpUe4o4i3bKBqJ+cbCJWZOG9fvEdl2qQFeSn7jAebrWOp8GBn4sU5CxHgpk7zcvRytBTkJnCC1zVxM6Brc05rUMIzcozVVAqlgjbKjdfnTi0dohdMPjSdLBBKkEEN+Il63SEN9LBEAUUL/GFNods6wVXoUhymxoj0Qj4TNF3DX3CDbop6Sxhkq7GPW/p/LHt2q+ltbMUrtIVs5MDS3MNfh/oMpQmddvGE/J1aai0v30HRwdIj8VWGiKD6PTzLFkkS9m0TGJ1wQoLAodIEC/fcQOsGm8fO1qyOCB8uF46dhtU/5DDhkGs6+RT6j8URDdH2XCFMvFZZeagV+QnehQDe1awtY7OXHPJxbSL/N/y/kf8gtoXqifQ2v5rPKsTLn6VKsPWq7rDKf+nUIoL/X7mcpPQQfFtmwlMZTEjVa+gTnzActYMF45Xour1te51bEZ2ElG8zAPNN+hvtkNTtT+UobUhcMGG+blFP6X/PR6QNerVNQ9PeuidquKZGHXKEz7iNv1n/mzO6NaPyac5EtLYJHmI6T1dB3Ss0Gr7dG2c72LWLHsICzA="
