git:
  depth: 1
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- npm set progress=false
- npm install gulp-cli -g
- chmod +x ./deploy-gh-pages.sh
script: "./deploy-gh-pages.sh"
env:
  global:
    secure:  vJ5z5fFwmL0kkThY/T8uU4dlB9DdTYZCh1k4awvGzoZw5SmC2btug4h/yoDslVKek8zR1O+SjI11edrb7/Rh1V0hI/8VV9pUlsJOljsEZ9DNiMId3AyDzeXLJHpNM9l8R3R20f77HszXjYV3Pdj5O5AqXKRiuURYhSK/Tmkjm/DGz3O9L80E0sH0TLLHnE5UDUW2+NqXNiSaXI1MBlIRzOXoa2swnTVOSlhCxyUb53kuf5narertAUViDmtKYKXuc8SS808XRNhIaxtSRDmeMC1tZhaqFwnTbV1gQhqEsXT698XAy4PEjs8OvukGroRceWQ2hvDkpWcRS0z6Cds4WLdpj75i9KDbZgixnO74NVx+rD5LFQnQz5bIXcB0v6hje1FUvpo5weHhkcRZL1fXHUdV9aO269jSs580RfbS4oAztv+D6Kx7HT6zFSMOOQLABa4eOBNwk3IKrp54Zn4Ts2nke8ofPzELGl2c5AzhGeyEbsJzmyUj41tSpbPDXC035ZOzmFw8nBNqbXBXtOXoPeLSRrUjSfvu/374PXbfVXZPPfkrXgPWtftECI0KYGiP78QC/Hp2sAASgc8luh1WCx3XfI4Zj+b55rshVw+0DC883ZSFVRyri4/mkro0VUciBzatYdLzwjw0B97GLs04nAnYAn2jMt2pNk1wycrZ9RM=
