git:
  depth: 1
language: node_js
node_js:
  - '4.2'
  - 'stable'
cache:
  directories:
    - node_modules
before_script:
  - npm set progress=false
  - npm install gulp-cli -g
  - chmod +x ./deploy-gh-pages.sh
script: "./deploy-gh-pages.sh"
env:
  global:
    secure: nYLOj2haeUDYhE3D++DyhPz/zkMlsHDRYgB0BSl3r6kLAVAC3PXuNsdZDB3QpMlqkD0RafkDLZIyntYUIZAlvz4z9T18adqCV3186HWTWislUYYqxILh8Db/Zc1Jq84YaGyFh0wlfYQkBfDDYLerJVEnl/rtyqBhPajN8bhuHKTSfFvOrRqptUvcdKA8DnSbzpIy6sOsbECXZu2jsto4oYoKEiP8noQXhVie+fEDIKRa0xWMpEOWxl5qyOYLi6fRc9PyCp5Q9ZC22Fl+QQ/dpklmSTaKt4HanCzBeJwN2BLsHdE5nclfhcmgJO7Z6qqafhYCvdrrqSW8Owhul61LnqUdrKmwCzjalTM8z4FxcNTfJikE7RZS2tJjNwdoM7V6z+rO5jVGrOJu2LzymEHB8Hvf3M1oNVZK80b0TEL/5n5jNCUSmY13cwTvqMPOc4CecdTTJXJAZ1RKPhRXl33pAIDkx9JfZ25dOU2rDrU5fHcXd0FBTj6XYrdBoDxPxkmcoMcEfIGwVTh3jhPc7AZGGWufFxpyfDcTW3p1WwuZlLEtkgnGxoAjz31/bYhsBDhETNafytoectdshqPQ8IwxzIH2L07gzSMg1G/SZhIdgYaUGI3o112xLyKtP+6T+OPvCroByR9/57MfUgf/lurV0K0mf5d3/mtFTOULfhxgIiI=
